plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.newslit'
version = '0.0.1-SNAPSHOT'
description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'com.github.ben-manes.caffeine:caffeine'
    implementation 'com.mysql:mysql-connector-j'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
    implementation "com.deepl.api:deepl-java:1.12.0"
    implementation 'com.rometools:rome:2.1.0'
    implementation 'org.jsoup:jsoup:1.16.1'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation platform('com.oracle.database.jdbc:ojdbc-bom:23.3.0.23.09')
    implementation 'com.oracle.database.jdbc:ojdbc8'
    implementation 'com.oracle.database.jdbc:ucp'
    implementation 'com.oracle.database.security:oraclepki'
    implementation 'com.oracle.database.security:osdt_core'
    implementation 'com.oracle.database.security:osdt_cert'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'

    // Oracle Cloud SDK
    implementation 'com.oracle.oci.sdk:oci-java-sdk-common:3.30.0'
    implementation 'com.oracle.oci.sdk:oci-java-sdk-objectstorage:3.30.0'
    implementation 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey:3.30.0'

    // Jersey 2.x
    implementation 'org.glassfish.jersey.core:jersey-client:2.41'
    implementation 'org.glassfish.jersey.core:jersey-common:2.41'
    implementation 'org.glassfish.jersey.inject:jersey-hk2:2.41'
    implementation 'org.glassfish.jersey.connectors:jersey-apache-connector:2.41'
    implementation 'org.glassfish.jersey.media:jersey-media-json-jackson:2.41'

    // JAX-RS API 2.x
    implementation 'javax.ws.rs:javax.ws.rs-api:2.1.1'

    // JAXB (Java 11+ 필수)
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
}
tasks.named('test') {
    useJUnitPlatform()
}